//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpgradeHelpers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpgradeHelpers_VB6 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        /// Returns the instance of UpgradeHelpers_VB6
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UpgradeHelpers_VB6() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpgradeHelpers.UpgradeHelpers.Resources.UpgradeHelpers", typeof(UpgradeHelpers_VB6).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 'Artchivos de ayuda (*.chm;*.html)|*.chm;*.html'.
        /// </summary>
        public static string UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_OpenDialog_Filter {
            get {
                return ResourceManager.GetString("UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_OpenDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 'No se pudo hallar el archivo {0}. ¿Desea intentar hallarlo usted mismo?'.
        /// </summary>
        public static string UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_Question {
            get {
                return ResourceManager.GetString("UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 'Ayuda de Windows' (Windows Help).
        /// </summary>
        public static string UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_Question_Title {
            get {
                return ResourceManager.GetString("UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_Question_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 'No se pudo hallar el archivo de Ayuda {0}. Compruebe si existe en su disco; de lo contrario necesitará instalarlo de nuevo..'
        /// </summary>
        public static string UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_ValidationFailure {
            get {
                return ResourceManager.GetString("UpgradeHelpers_VB6_Help_HelpSupportClass_ValidateHelpFile_ValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 'Error al crear parche para el evento &apos;ItemClick&apos;. {0}.'
        /// </summary>
        public static string UpgradeHelpers_VB6_Help_ListViewHelper_PatchItemClickEvent_Err_Msg {
            get {
                return ResourceManager.GetString("UpgradeHelpers_VB6_Help_ListViewHelper_PatchItemClickEvent_Err_Msg", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the default drag image.
        /// </summary>
        public static System.Drawing.Icon DefaultDragImage
        {
            get {
                object obj = ResourceManager.GetObject("DefaultDragImage", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
